coverage:
  status:
    project:
      default:   
        informational: true
    patch:
      default:
        informational: true

comment:

    layout: "header, files, footer"
    hide_project_coverage: false
    behavior: "new"